### PR TITLE
Various optimizations around the listener

### PR DESCRIPTION
**Pull request by vigoo**
This is my take on https://github.com/zio/zio-zmx/issues/121.

- Adds a fixed rate to `untilNCollected` to avoid the spin loop
- Replaces `AtomicReference` to a `Ref` as it is only used from ZIO effects, especially if https://github.com/zio/zio-zmx/pull/139 gets merged. I applied the changes from that PR to this more or less
- Replaces `List` of metrics to `Chunk`, I started this because I did not like the append to `List` in `poll` and then felt like it will be better to just change the type everywhere.
- `ServiceSpec` did not test anything as there were no asserts and it used the `TestClock` while the implementation explicitly uses the live clock so I changed that to a more meaningful suite

The `collect` may need additional changes to drain the whole ring buffer if there is at least one chunk of metrics to send out, as with the fixed rate added the ring buffer can easily overloaded. I would rather do this after some sleep though :)

### CODE REVIEW

**Comment by adamgfraser** [comment]
Looks great!

**Comment by adamgfraser** [comment]
Can you resolve conflicts? Otherwise let's get this merged!

**Comment by vigoo** [comment]
Some new tests are failing after the merge, I believe because of the new draining behavior, will fix tomorrow

**Comment by vigoo** [comment]
Note: it's not the draining, there is a weird flakyness, in the failing test sometimes `poll` runs even if the `TestClock` is not moved at all.

**Review by adamgfraser — APPROVED** [review]

**Pull request merged**
