### PR TITLE
Implement MetricAspect.observeDurations

### PR DESCRIPTION
**Pull request by adamgfraser**
A metric aspect that tracks the time it takes for an effect to execute and records the execution times in a histogram.

### CODE REVIEW

**Comment by gavares** [comment]
Won't this not capture when an error occurs? I think, from an observability standpoint, there is generally correlation between deviations in observed duration and errors. Ideally the observe would be performed in either case.

**Comment by adamgfraser** [comment]
We definitely could do that. I would tend to think that would best be tracked by another metric entirely that captures errors and then this captures timing of successful results. `ZIO.timed` for example only times effects that successfully complete execution.

**Comment by gavares** [comment]
Fair enough. Looking forward to getting this merged and testing it out. Thanks again for the quick turnaround.

**Review by gavares — APPROVED** [review]
If my approval carries any weight here, I certainly approve.

**Review by gavares — APPROVED** [review]

**Pull request merged**
