### PR TITLE
Removing zio-nio from UDPClient #102

### PR DESCRIPTION
**Pull request by benetis**
PR together with @ahoy-jon (pair programming)

@adamgfraser is wrapping `java.nio` in `ZDatagramChannel` acceptable?

### CODE REVIEW

**Comment by adamgfraser** [comment]
@benetis @ahoy-jon Wow that's awesome! Yes the key thing is not to have any internal dependency so I think if we want to wrap data types to provide a more idiomatic way of working with them that is fine. We can always optimize later if we think we can get more efficiency from a lower level implementation. This one is so minimal I don't know if it even needs its own package. You could probably just put it as a helper somewhere.

**Comment by ahoy-jon** [comment]
@adamgfraser `object zio.zmx.JavaNioUtils` ?

Like 

```scala
package zio.zmx

import zio.{ Chunk, Task }

import java.nio.ByteBuffer
import java.nio.channels.DatagramChannel

private[zmx] object JavaNioUtils {
  class ZDatagramChannel(private val datagramChannel: DatagramChannel) {
    def write(chk: Chunk[Byte]): Task[Long] = execute(_.write(ByteBuffer.wrap(chk.toArray)).toLong)

    def execute[B](f: DatagramChannel => B): Task[B] = Task(f(datagramChannel))
  }

  object ZDatagramChannel {
    def apply(datagramChannel: DatagramChannel): ZDatagramChannel = new ZDatagramChannel(datagramChannel)
  }
  /* ... */
}
```

**Comment by ahoy-jon** [comment]
(I will need those wrappers a bit more to tackle #100)

**Comment by adamgfraser** [comment]
Yes I think something like that is perfect.

**Comment by ahoy-jon** [comment]
opened a PR on @benetis repo for that: https://github.com/benetis/zio-zmx/pull/1/files

**Comment by benetis** [comment]
> opened a PR on @benetis repo for that: https://github.com/benetis/zio-zmx/pull/1/files

thanks, merged into this PR

**Comment by adamgfraser** [comment]
Can you resolve conflicts and then this will be good to go?

**Comment by benetis** [comment]
@adamgfraser resolved

**Review by adamgfraser — APPROVED** [review]
Nice!

**Pull request merged**
